- [3.4](#3.4)
- [3.5](#3.5)
- [3.6](#3.6)

- [4.1, 4.2](#4.1,-4.2)
- [5.1](#5.1)
- [5.2](#5.2)
- [5.3](#5.3)

- [6.2](#6.2)
- [6.3](#6.3)
- [6.4](#6.4)
- [KNN1](#KNN1)
- [KNN2](#KNN2)
- [6.5](#6.5)
- [7.4](#7.4)

3.4
---

In [2]:
numbers = [10, 2, 4, 8, 1.7]
squared_numbers = []

for i, x in enumerate(numbers):
    print('Il numero in posizione {} è {}'.format(i, x))
    squared_numbers += [x**2]
    
squared_numbers

Il numero in posizione 0 è 10
Il numero in posizione 1 è 2
Il numero in posizione 2 è 4
Il numero in posizione 3 è 8
Il numero in posizione 4 è 1.7


[100, 4, 16, 64, 2.8899999999999997]

3.5
---

In [2]:
names = ['francesco', 'elisa', 'alessandro', 'giovanni', 'maria teresa']
indexed_sorted_names = [[i, n] for i, n in enumerate(sorted(names))]

indexed_sorted_names

[[0, 'alessandro'],
 [1, 'elisa'],
 [2, 'francesco'],
 [3, 'giovanni'],
 [4, 'maria teresa']]

3.6
---

In [3]:
numbers = [10, 2, 4, 8, 1.7]
squared_numbers = [x**2 for x in numbers]

squared_numbers

[100, 4, 16, 64, 2.8899999999999997]

4.1, 4.2
---

In [ ]:
lst = [3,6,5,8,12]

for element in lst:
    if element**2 % 2 == 0 and element**2 % 3 == 0:
        print('Il quadrato di {} è {}, che è multiplo sia di 2 che di 3'.format(element, element**2))
    elif element**2 % 2 == 0:
        print('Il quadrato di {} è {}, che è multiplo di 2 ma non di 3'.format(element, element**2))
    elif element**2 % 3 == 0:
        print('Il quadrato di {} è {}, che è multiplo di 3 ma non di 2'.format(element, element**2))
    else:
        print('Il quadrato di {} è {}, che non è multiplo né di 2 né di 3'.format(element, element**2))
        
print('\n*******************\n')

multiples_of_2 = [element**2 for element in lst if element**2 % 2 == 0]
multiples_of_3 = [element**2 for element in lst if element**2 % 3 == 0]
multiples_of_2_and_not_of_3 = [element**2 for element in lst if element**2 % 2 == 0 and not element**2 % 3 == 0]

print(multiples_of_2)
print(multiples_of_3)
print(multiples_of_2_and_not_of_3)

5.1
---

In [ ]:
heights = {}
heights['Mount Everest'] = 8858
heights['K2'] = 8611
heights['Kangchenjunga'] = 8586

for mountain, height in heights.items():
    print('{} è alta {}'.format(mountain, height))
    
for i, mountain in enumerate(sorted(heights.keys())):
    print('La montagna numero {} è {} ed è alta {}'.format(i+1, mountain, heights[mountain]))

5.2
---

In [ ]:
mountains = []

mountains += [{'name':'Mount Everest', 'height':8858, 'country':'Nepal'}]
mountains += [{'name':'K2', 'height':8611, 'country':'Pakistan'}]
mountains += [{'name':'Kangchenjunga', 'height':8586, 'country':'Nepal'}]

for i, m in enumerate(mountains):
    print('La montagna numero {} è {}, è alta {} e si trova in {}'.format(i,
                                                                          m['name'],
                                                                          m['height'],
                                                                          m['country']))

In [ ]:
mountain_names = [m['name'] for m in mountains]
mountain_heights = [m['height'] for m in mountains]

heights = {}

for i,n in enumerate(mountain_names):
    heights[n] = mountain_heights[i]
    
print(heights)

5.3
---

In [37]:
def show_property_info(prop):
    print('Paese: {}'.format(prop['country']))
    print('Estensione (mq): {}'.format(prop['extension']))
    print('Terreno annesso?: {}'.format('Sì' if prop['has_land'] else 'No'))
    print('Prezzo: {:.2f}'.format(prop['price']))

In [38]:
properties = []

r1 = {'country':'Italia',    'extension':2000,  'has_land':False, 'price':10}
r2 = {'country':'Spagna',    'extension':12000, 'has_land':False, 'price':125}
r3 = {'country':'Argentina', 'extension':50000, 'has_land':True,  'price':300}

properties += [r1, r2, r3]

for i, prop in enumerate(properties):
    print(f'\nProprietà #{i}')#sintassi alternativa a format, disponibile da Python 3.6
    show_property_info(prop)


Proprietà #0
Paese: Italia
Estensione (mq): 2000
Terreno annesso?: No
Prezzo: 10.00

Proprietà #1
Paese: Spagna
Estensione (mq): 12000
Terreno annesso?: No
Prezzo: 125.00

Proprietà #2
Paese: Argentina
Estensione (mq): 50000
Terreno annesso?: Sì
Prezzo: 300.00


In [ ]:
###################

6.2
---

In [2]:
import numpy as np
import numpy.random as rdm
from math import sqrt

def py_std(x):
    mean_val = sum(x) / len(x)
    return sqrt(sum((val-mean_val)**2 for val in x) / len(x))

large_array = rdm.normal(size=(1000000,))

print(py_std(large_array))
print(np.std(large_array))
%timeit py_std(large_array)
%timeit np.std(large_array)

0.9992693936220786
0.9992693936220851
323 ms ± 1.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.3 ms ± 15.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


6.3
---

In [1]:
import numpy as np
import numpy.random as rdm

n_frames = 50
n_pixel_x = 5
n_pixel_y = 5
movie = rdm.randint(0, 256, (n_frames, n_pixel_x, n_pixel_y))
print(movie)

[[[175  37 192 120 181]
  [ 15 114 217 168  95]
  [190 174 175 107 203]
  [250 210 189 229  47]
  [169 110 130 148 160]]

 [[ 72 194 176 105 244]
  [ 16 250 136 153  28]
  [110  61 159  98   5]
  [ 90 233 151 244 235]
  [136 123  25 225 141]]

 [[ 28 168 112 247 165]
  [ 58  69 212 204 153]
  [174  90 164  52  28]
  [ 92 226 183 255 100]
  [190 169 199 242 201]]

 ...

 [[148  81 144  29   5]
  [219 118 185  42 248]
  [248 136  94  25  55]
  [135  37  51  90   4]
  [ 66 188  50 109  93]]

 [[ 78 192 135  75 109]
  [ 85  27  48  51  25]
  [135 161 227  71 177]
  [229 240 251 114 152]
  [129  27 187 131 140]]

 [[157  25 163 205  31]
  [193 138  83 111 183]
  [ 43 245 163 253 139]
  [ 65  35  44 248 135]
  [ 98  24 148 225 123]]]


In [2]:
print(movie.shape)

(50, 5, 5)


In [3]:
pixel_mean_intensity = np.mean(movie, axis=0)
print(pixel_mean_intensity)
print(pixel_mean_intensity.shape)

[[114.48 110.74 142.62 114.56 123.72]
 [124.78 132.6  121.52 111.9  118.92]
 [129.82 121.78 113.22 129.1  147.8 ]
 [139.24 128.6  149.04 146.88 132.04]
 [124.98 124.86 129.32 143.84 112.62]]
(5, 5)


6.4
---

In [1]:
import numpy as np
import numpy.random as rdm

values = rdm.normal(5, 3, 1000000)

#sottraggo 5 e guardo se ha funzionato
print(round(np.mean(values), 4))
values -= 5
print(round(np.mean(values), 4))

#implemento deviazione std e confronto con np.std
residuals = values - np.mean(values)
squared_residuals = residuals**2
variance = np.sum(squared_residuals) / values.size
print(np.std(values), np.sqrt(variance))

4.9992
-0.0008
3.001901282433962 3.001901282433962


KNN1
---

In [7]:
import numpy as np

X_train = np.array([[1,2,3],
                    [0,2,-1],
                    [-1,2,3],
                    [3,1,3]])

x_new = np.array([1,1,2])

y_train = np.array([0,1,0,1])

print(X_train)
print(y_train)
print(x_new)

[[ 1  2  3]
 [ 0  2 -1]
 [-1  2  3]
 [ 3  1  3]]
[0 1 0 1]
[1 1 2]


In [8]:
distances = [np.sqrt(np.sum((x - x_new) ** 2)) for x in X_train]#riga per riga
distances = np.round(distances, 1)
print(distances)

[1.4 3.3 2.4 2.2]


Posso calcolare le distanze in modo ancora più compatto. Definita la *Norma* di un vettore $d$-dimensionale,

$$\|x\|_2 := \sqrt{\sum_{i=1}^d x_i^2},$$

si può dire che la distanza euclidea tra due vettori $x$ e $x'$ è la norma del *vettore differenza* $x - x'$:

$$D(x, x') = \sqrt{\sum_{i=1}^{d}(x_i-x'_i)^2} = \|x - x'\|_2.$$

Proviamo intanto ad operare vettorialmente.

In [19]:
X_train - x_new#vettori differenza

array([[ 0,  1,  1],
       [-1,  1, -3],
       [-2,  1,  1],
       [ 2,  0,  1]])

In [20]:
(X_train - x_new) ** 2#differenze al quadrato

array([[0, 1, 1],
       [1, 1, 9],
       [4, 1, 1],
       [4, 0, 1]])

In [21]:
np.sum((X_train - x_new) ** 2, axis=1)#somma (lungo le colonne) degli scarti al quadrato

array([ 2, 11,  6,  5])

In [25]:
distances = np.sqrt(np.sum((X_train - x_new) ** 2, axis=1))#tutto vettoriale
distances = np.round(distances, 1)
print(distances)

[1.4 3.3 2.4 2.2]


Volendo, tutto in una riga:

In [24]:
print(np.round(np.sqrt(np.sum((X_train - x_new) ** 2, axis=1)), 1))

[1.4 3.3 2.4 2.2]


Adesso utilizziamo la funzione *norm* di numpy.

In [26]:
from numpy.linalg import norm

vec = np.random.random((5,))
print(vec)
print(np.sqrt(np.sum(vec**2)))
print(norm(vec))

[0.61306346 0.90234858 0.09928035 0.96980907 0.65314004]
1.6022040728828197
1.6022040728828197


In [29]:
print(np.round(norm(X_train - x_new, axis=1), 1))#utilizzando la norma vettorialmente

[1.4 3.3 2.4 2.2]


**Nota**: abbiamo smesso di scrivere cicli for!

KNN2
---

In [34]:
people = np.array([[1.60, 66],
                   [1.60, 63],
                   [1.90, 67]])

print(people)

[[ 1.6 66. ]
 [ 1.6 63. ]
 [ 1.9 67. ]]


In [35]:
A, B, C = people
print(A)
print(B)
print(C)

[ 1.6 66. ]
[ 1.6 63. ]
[ 1.9 67. ]


In [36]:
print(norm(A-B))
print(norm(A-C))

3.0
1.0440306508910548


In [37]:
def scale_01(column):
    return (column - np.min(column)) / (np.max(column) - np.min(column))

scaled_height = scale_01(people[:, 0])
scaled_weight = scale_01(people[:, 1])

print(scaled_height)
print(scaled_weight)

[0. 0. 1.]
[0.75 0.   1.  ]


In [38]:
scaled_people = np.vstack([scaled_height, scaled_weight])
print(scaled_people)

[[0.   0.   1.  ]
 [0.75 0.   1.  ]]


In [39]:
scaled_people = scaled_people.T#trasposizione
print(scaled_people)

[[0.   0.75]
 [0.   0.  ]
 [1.   1.  ]]


Scriviamo tutto in modo più veloce e compatto, utilizzando il calcolo vettoriale.

In [46]:
print(people)

[[ 1.6 66. ]
 [ 1.6 63. ]
 [ 1.9 67. ]]


In [47]:
print(np.min(people, axis=0))#minimo per colonna (cioè, 'lungo le righe')

[ 1.6 63. ]


In [49]:
print(people - np.min(people, axis=0))

[[0.  3. ]
 [0.  0. ]
 [0.3 4. ]]


In [52]:
print(np.max(people, axis=0) - np.min(people, axis=0))

[0.3 4. ]


In [53]:
scaled_people = (people - np.min(people, axis=0)) / (np.max(people, axis=0) - np.min(people, axis=0))
print(scaled_people)

[[0.   0.75]
 [0.   0.  ]
 [1.   1.  ]]


In [55]:
scaled_A, scaled_B, scaled_C = scaled_people
print(scaled_A)
print(scaled_B)
print(scaled_C)

[0.   0.75]
[0. 0.]
[1. 1.]


In [56]:
print(norm(scaled_A-scaled_B))
print(norm(scaled_A-scaled_C))

0.75
1.0307764064044151


6.5
---

In [60]:
import numpy as np
from numpy.linalg import norm

np.random.seed(0)#fisso il generatore casuale per la riproducibilità dell'esperimento

def KNN(k, X, y, x):
    distances = norm(X - x, axis=1)
    sorted_labels = y[distances.argsort()]
    return np.argmax(np.bincount(sorted_labels[:k]))

def one_line_KNN(k, X, y, x):
    return np.argmax(np.bincount(y[norm(X - x, axis=1).argsort()][:k]))

X_train = np.random.random((7,4))
y_train = np.random.randint(0, 2, (7))
x_new = np.random.random((4,))

print('Matrice delle feature:\n', X_train)

print('\nVettore delle etichette:', y_train)

print('\nNuovo esempio da classificare:', x_new)

print('\nPredizione (k=3):', one_line_KNN(3, X_train, y_train, x_new))
print('Predizione (k=5):', one_line_KNN(5, X_train, y_train, x_new))

Matrice delle feature:
 [[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]
 [0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]]

Vettore delle etichette: [1 0 0 1 1 0 1]

Nuovo esempio da classificare: [0.73691818 0.21655035 0.13521817 0.32414101]

Predizione (k=3): 1
Predizione (k=5): 0


7.4
---

In [11]:
from sklearn import datasets, neighbors
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler

#Carico il dataset
digits = datasets.load_digits()
X, y = digits['data'], digits['target']

#Separo train e test
X, y = shuffle(X, y, random_state=123)
X_tr, X_val, X_test = X[:500], X[500:1000], X[1000:]
y_tr, y_val, y_test = y[:500], y[500:1000], y[1000:]

#Scalo i dati
scaler = StandardScaler()
X_tr_scaled = scaler.fit_transform(X_tr)
X_val_scaled = scaler.transform(X_val)

#Valuto accuratezza dei modelli sul set di validazione
for k in [1,2,3,5,10]:
    val_acc = neighbors.KNeighborsClassifier(n_neighbors=k).fit(X_tr_scaled, y_tr).score(X_val_scaled, y_val)
    print('Validation accuracy with k {}: {:.2f}'.format(k, val_acc))                  

Validation accuracy with k 1: 0.97
Validation accuracy with k 2: 0.96
Validation accuracy with k 3: 0.98
Validation accuracy with k 5: 0.97
Validation accuracy with k 10: 0.95


In [12]:
import numpy as np

#Rifitto su tutto il training set
X_train, y_train = np.vstack([X_tr, X_val]), np.hstack([y_tr, y_val])
X_train_scaled = scaler.fit_transform(X_train)
best_model = neighbors.KNeighborsClassifier(n_neighbors=3).fit(X_train_scaled,
                                                               y_train)

#Valuto accuratezza del miglior modello sul test set
X_test_scaled = scaler.transform(X_test)
print('Test accuracy with selected k: {:.2f}'.format(best_model.score(X_test_scaled,
                                                                      y_test))) 

Test accuracy with selected k: 0.97


<script>
  $(document).ready(function(){
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('div.prompt').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#999; background:#fff;">
Created with Jupyter, delivered by Fastly, rendered by Rackspace.
</footer>