5.4
---

In [3]:
numbers = [10, 2, 4, 8, 1.7]
squared_numbers = []

for i, x in enumerate(numbers):
    print('The number with index {} is {}'.format(i, x))
    squared_numbers += [x**2]
    
squared_numbers

The number with index 0 is 10
The number with index 1 is 2
The number with index 2 is 4
The number with index 3 is 8
The number with index 4 is 1.7


[100, 4, 16, 64, 2.8899999999999997]

5.5
---

In [4]:
names = ['francesco', 'elisa', 'alessandro', 'giovanni', 'maria teresa']
indexed_sorted_names = [[i, n] for i, n in enumerate(sorted(names))]

indexed_sorted_names

[[0, 'alessandro'],
 [1, 'elisa'],
 [2, 'francesco'],
 [3, 'giovanni'],
 [4, 'maria teresa']]

5.6
---

In [5]:
numbers = [10, 2, 4, 8, 1.7]
squared_numbers = [x**2 for x in numbers]

squared_numbers

[100, 4, 16, 64, 2.8899999999999997]

6.1, 6.2
---

In [6]:
lst = [3,6,5,8,12]

for element in lst:
    if element**2 % 2 == 0 and element**2 % 3 == 0:
        print('The square of {} is {}, which is a multiple of both 2 and 3'.format(element, element**2))
    elif element**2 % 2 == 0:
        print('The square of {} is {}, which is a multiple of 2 but not of 3'.format(element, element**2))
    elif element**2 % 3 == 0:
        print('The square of {} is {}, which is a multiple of 3 but not of 2'.format(element, element**2))
    else:
        print('The square of {} is {}, which is neither a multiple of 2 nor 3'.format(element, element**2))
        
print('\n**************************************************************\n')

multiples_of_2 = [element**2 for element in lst if element**2 % 2 == 0]
multiples_of_3 = [element**2 for element in lst if element**2 % 3 == 0]
multiples_of_2_and_not_of_3 = [element**2 for element in lst if element**2 % 2 == 0 and not element**2 % 3 == 0]

print(multiples_of_2)
print(multiples_of_3)
print(multiples_of_2_and_not_of_3)

The square of 3 is 9, which is a multiple of 3 but not of 2
The square of 6 is 36, which is a multiple of both 2 and 3
The square of 5 is 25, which is neither a multiple of 2 nor 3
The square of 8 is 64, which is a multiple of 2 but not of 3
The square of 12 is 144, which is a multiple of both 2 and 3

**************************************************************

[36, 64, 144]
[9, 36, 144]
[64]


In [ ]:
#inizio dizionari

7.1
---

In [7]:
heights = {}
heights['Mount Everest'] = 8858
heights['K2'] = 8611
heights['Kangchenjunga'] = 8586

for mountain, height in heights.items():
    print('{} è alta {}'.format(mountain, height))
    
for i, mountain in enumerate(sorted(heights.keys())):
    print('La montagna numero {} è {} ed è alta {}'.format(i+1, mountain, heights[mountain]))

Mount Everest è alta 8858
K2 è alta 8611
Kangchenjunga è alta 8586
La montagna numero 1 è K2 ed è alta 8611
La montagna numero 2 è Kangchenjunga ed è alta 8586
La montagna numero 3 è Mount Everest ed è alta 8858


7.2
---

In [8]:
mountains = []

mountains += [{'name':'Mount Everest', 'height':8858, 'country':'Nepal'}]
mountains += [{'name':'K2', 'height':8611, 'country':'Pakistan'}]
mountains += [{'name':'Kangchenjunga', 'height':8586, 'country':'Nepal'}]

for i, m in enumerate(mountains):
    print('La montagna numero {} è {}, è alta {} e si trova in {}'.format(i,
                                                                          m['name'],
                                                                          m['height'],
                                                                          m['country']))

La montagna numero 0 è Mount Everest, è alta 8858 e si trova in Nepal
La montagna numero 1 è K2, è alta 8611 e si trova in Pakistan
La montagna numero 2 è Kangchenjunga, è alta 8586 e si trova in Nepal


In [9]:
mountain_names = [m['name'] for m in mountains]
mountain_heights = [m['height'] for m in mountains]

heights = {}

for i,n in enumerate(mountain_names):
    heights[n] = mountain_heights[i]
    
print(heights)

{'Mount Everest': 8858, 'K2': 8611, 'Kangchenjunga': 8586}


7.3
---

In [5]:
def show_estate_info(e):
    print('Paese: {}'.format(e['country']))
    print('Estensione (mq): {}'.format(e['extension']))
    print('Terreno annesso?: {}'.format('Sì' if e['has_land'] else 'No'))
    print('Prezzo: {}K Euro'.format(e['price']))

In [9]:
estates = []

e1 = {'country':'Italia',    'extension':2000,  'has_land':False, 'price':10}
e2 = {'country':'Spagna',    'extension':12000, 'has_land':False, 'price':125}
e3 = {'country':'Argentina', 'extension':50000, 'has_land':True,  'price':300}

estates += [e1, e2, e3]

for i, e in enumerate(estates):
    print(f'\nImmobile #{i}')#sintassi alternativa a format, disponibile da Python 3.6
    show_estate_info(e)


Immobile #0
Paese: Italia
Estensione (mq): 2000
Terreno annesso?: No
Prezzo: 10K Euro

Immobile #1
Paese: Spagna
Estensione (mq): 12000
Terreno annesso?: No
Prezzo: 125K Euro

Immobile #2
Paese: Argentina
Estensione (mq): 50000
Terreno annesso?: Sì
Prezzo: 300K Euro


In [ ]:
################### fine dizionari, inizio numpy

10.2
---

In [22]:
import numpy as np
import numpy.random as rdm

n_frames = 50
n_pixel_x = 5
n_pixel_y = 5
movie = rdm.randint(0, 256, (n_frames, n_pixel_x, n_pixel_y))

movie

array([[[ 64,  14,  27,  58, 221],
        [219, 209,  50, 121, 198],
        [ 45,  39,  12, 224, 207],
        [148,   2,   4, 128, 183],
        [213, 123,  87,  30, 114]],

       [[115,  53,   6, 150, 200],
        [106,  55, 148,  27,  26],
        [ 75,  13, 233,  82, 135],
        [199, 157, 146,  75, 255],
        [103, 193,   8, 223, 165]],

       [[254,  22, 187,  71,  79],
        [159, 125, 193,  95, 168],
        [234, 183,  10, 244, 208],
        [163,  79, 111,  97, 124],
        [252, 202, 136,  39,  55]],

       ...,

       [[105,  64,  30, 109,  84],
        [205, 127,   1, 163, 106],
        [247,  52, 170,  25,   9],
        [139,  84,  16, 104, 152],
        [208,  68, 195,  16,  51]],

       [[ 65, 169,  28,  92, 241],
        [157,  28, 217,   4,  81],
        [  9,   1, 159,  92, 148],
        [ 80, 144, 197,  75, 230],
        [149,  99, 198, 133, 138]],

       [[ 58, 191,  44, 133, 188],
        [197,  44, 173, 236,  10],
        [ 18, 216,  21,  80, 255

In [23]:
movie.shape

(50, 5, 5)

In [24]:
pixel_mean_intensity = np.mean(movie, axis=0)
pixel_mean_intensity

array([[120.96, 106.36, 113.72, 127.86, 112.8 ],
       [129.88, 122.18, 116.76, 113.98, 133.6 ],
       [120.84, 134.64, 119.06, 122.3 , 140.8 ],
       [109.6 , 127.5 , 108.12, 134.06, 140.74],
       [130.32, 140.62, 138.4 , 120.42, 135.66]])

In [25]:
pixel_mean_intensity.shape

(5, 5)

11.1
---

In [6]:
import numpy as np

X_train = np.array([[1,2,3],
                    [0,2,-1],
                    [-1,2,3],
                    [3,1,3]])

x_test = np.array([1,1,2])

In [7]:
X_train

array([[ 1,  2,  3],
       [ 0,  2, -1],
       [-1,  2,  3],
       [ 3,  1,  3]])

In [8]:
x_test

array([1, 1, 2])

In [9]:
for x in X_train:
    print(x)

[1 2 3]
[ 0  2 -1]
[-1  2  3]
[3 1 3]


In [10]:
for x in X_train:
    print(np.sqrt(np.sum((x - x_test) ** 2)).round(1))#distance

1.4
3.3
2.4
2.2


In [11]:
x_test

array([1, 1, 2])

In [12]:
for x in X_train:
    
    print('\ntrain sample: ', x)

    diff = x - x_test    
    print('component-wise differences:', diff)
    
    squared_diff = (x - x_test) ** 2    
    print('squared differences:', squared_diff)
    
    diff_sum = np.sum((x - x_test) ** 2)
    print('sum of squared differences:', diff_sum)
    
    distance = np.sqrt(np.sum((x - x_test) ** 2))
    print('distance:', distance.round(1))


train sample:  [1 2 3]
component-wise differences: [0 1 1]
squared differences: [0 1 1]
sum of squared differences: 2
distance: 1.4

train sample:  [ 0  2 -1]
component-wise differences: [-1  1 -3]
squared differences: [1 1 9]
sum of squared differences: 11
distance: 3.3

train sample:  [-1  2  3]
component-wise differences: [-2  1  1]
squared differences: [4 1 1]
sum of squared differences: 6
distance: 2.4

train sample:  [3 1 3]
component-wise differences: [2 0 1]
squared differences: [4 0 1]
sum of squared differences: 5
distance: 2.2


In [13]:
X_train - x_test#component-wise differences

array([[ 0,  1,  1],
       [-1,  1, -3],
       [-2,  1,  1],
       [ 2,  0,  1]])

In [14]:
(X_train - x_test) ** 2#squared differences

array([[0, 1, 1],
       [1, 1, 9],
       [4, 1, 1],
       [4, 0, 1]])

In [15]:
np.sum((X_train - x_test) ** 2, axis=1)#sum of squared differences

array([ 2, 11,  6,  5])

In [16]:
np.sqrt(np.sum((X_train - x_test) ** 2, axis=1))#distances

array([1.41421356, 3.31662479, 2.44948974, 2.23606798])

In [17]:
np.sqrt(np.sum((X_train - x_test) ** 2, axis=1)).round(1)#rounded distances

array([1.4, 3.3, 2.4, 2.2])

14.3
---

In [30]:
#import libraries
from sklearn import datasets, neighbors
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor as KNN
from sklearn.metrics import mean_absolute_error

#load data
boston = datasets.load_boston()
X, y = boston['data'], boston['target']

print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [31]:
#scale features between 0 and 1
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

#split data into train and test
X, y = shuffle(X, y, random_state=0)
X_train, X_test = X[:400], X[400:]
y_train, y_test = y[:400], y[400:]

#train the model
model = KNN(n_neighbors=3).fit(X_train, y_train)

#get predictions and assess model performance
predictions = model.predict(X_test)
mae = mean_absolute_error(y_test, predictions)
print('Model accuracy on test set: {:.3f}'.format(mae))

Model accuracy on test set: 2.845


15.1
---

In [50]:
import pandas as pd

df = pd.read_csv('data/nyc_rolling_sales.csv')
df.head()

BOROUGH   NEIGHBORHOOD                      BUILDING CLASS CATEGORY  \
0  MANHATTAN  ALPHABET CITY  07 RENTALS - WALKUP APARTMENTS                
1  MANHATTAN  ALPHABET CITY  07 RENTALS - WALKUP APARTMENTS                
2  MANHATTAN  ALPHABET CITY  07 RENTALS - WALKUP APARTMENTS                
3  MANHATTAN  ALPHABET CITY  07 RENTALS - WALKUP APARTMENTS                
4  MANHATTAN  ALPHABET CITY  08 RENTALS - ELEVATOR APARTMENTS              

  TAX CLASS AT PRESENT  BLOCK  LOT BUILDING CLASS AT PRESENT  \
0                   2A    392    6                        C2   
1                   2B    402   21                        C4   
2                   2A    404   55                        C2   
3                   2B    406   32                        C4   
4                    2    387  153                        D9   

                  ADDRESS  ZIP CODE  RESIDENTIAL UNITS  COMMERCIAL UNITS  \
0            153 AVENUE B     10009                  5                 0   
1     154 EAST 7TH STREET     10009                 10                 0   
2  301 EAST 10TH   STREET     10009                  6                 0   
3            210 AVENUE B     10009                  8                 0   
4     629 EAST 5TH STREET     10009                 24                 0   

   LAND SQUARE FEET  GROSS SQUARE FEET  YEAR BUILT  TAX CLASS AT TIME OF SALE  \
0              1633               6440        1900                          2   
1              2272               6794        1913                          2   
2              2369               4615        1900                          2   
3              1750               4226        1920                          2   
4              4489              18523        1920                          2   

  BUILDING CLASS AT TIME OF SALE            SALE DATE  SALE PRICE  
0                             C2  2017-07-19 00:00:00     6625000  
1                             C4  2016-09-23 00:00:00     3936272  
2                             C2  2016-11-17 00:00:00     8000000  
3                             C4  2016-09-23 00:00:00     3192840  
4                             D9  2016-11-07 00:00:00    16232000

Nell'ottica di predire il prezzo di una unità immobiliare o di un edificio, alcune colonne risultano inutili o ridondanti. Per esempio:
- l'informazione data da *BOROUGH* è contenuta (con maggiore dettaglio) anche in *NEIGHBORHOOD* e in *ZIP CODE*; quale colonna scegliamo?
- lo stesso vale (vedi glossario qui sotto) per le colonne relative alla *BUILDING CLASS*
- *ADDRESS* e la coppia *BLOCK*+*LOT* (vedi glossario) sono identificativi *univoci*, e non sono adatti ad essere usati come feature; perchè?
- l'utilità di *SALE DATE* dipende dal contesto: come la possiamo usare?
- ...

Glossario: https://www1.nyc.gov/assets/finance/downloads/pdf/07pdf/glossary_rsf071607.pdf.

In [51]:
df.columns

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY',
       'TAX CLASS AT PRESENT', 'BLOCK', 'LOT', 'BUILDING CLASS AT PRESENT',
       'ADDRESS', 'ZIP CODE', 'RESIDENTIAL UNITS', 'COMMERCIAL UNITS',
       'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT',
       'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE',
       'SALE DATE', 'SALE PRICE'],
      dtype='object')

In [52]:
df = df.drop(columns=['NEIGHBORHOOD',
                      'ZIP CODE',
                      'BLOCK',
                      'LOT',
                      'ADDRESS',
                      'BUILDING CLASS AT PRESENT',
                      'BUILDING CLASS AT TIME OF SALE',
                      'TAX CLASS AT PRESENT',
                      'SALE DATE'])

In [53]:
df.head()

BOROUGH                      BUILDING CLASS CATEGORY  RESIDENTIAL UNITS  \
0  MANHATTAN  07 RENTALS - WALKUP APARTMENTS                               5   
1  MANHATTAN  07 RENTALS - WALKUP APARTMENTS                              10   
2  MANHATTAN  07 RENTALS - WALKUP APARTMENTS                               6   
3  MANHATTAN  07 RENTALS - WALKUP APARTMENTS                               8   
4  MANHATTAN  08 RENTALS - ELEVATOR APARTMENTS                            24   

   COMMERCIAL UNITS  LAND SQUARE FEET  GROSS SQUARE FEET  YEAR BUILT  \
0                 0              1633               6440        1900   
1                 0              2272               6794        1913   
2                 0              2369               4615        1900   
3                 0              1750               4226        1920   
4                 0              4489              18523        1920   

   TAX CLASS AT TIME OF SALE  SALE PRICE  
0                          2     6625000  
1                          2     3936272  
2                          2     8000000  
3                          2     3192840  
4                          2    16232000

In [54]:
df.shape

(29280, 9)

Passiamo alla codifica one-hot delle feature nominali.

In [55]:
df = pd.get_dummies(df,
                    prefix=['BOR',
                            'BC',
                            'TC'],#nuovi prefissi comuni
                    columns=['BOROUGH',
                             'BUILDING CLASS CATEGORY',
                             'TAX CLASS AT TIME OF SALE'])#lista colonne da codificare

df.head()

RESIDENTIAL UNITS  COMMERCIAL UNITS  LAND SQUARE FEET  GROSS SQUARE FEET  \
0                  5                 0              1633               6440   
1                 10                 0              2272               6794   
2                  6                 0              2369               4615   
3                  8                 0              1750               4226   
4                 24                 0              4489              18523   

   YEAR BUILT  SALE PRICE  BOR_BRONX  BOR_BROOKLYN  BOR_MANHATTAN  BOR_QUEENS  \
0        1900     6625000          0             0              1           0   
1        1913     3936272          0             0              1           0   
2        1900     8000000          0             0              1           0   
3        1920     3192840          0             0              1           0   
4        1920    16232000          0             0              1           0   

   ...  BC_34 THEATRES                                  \
0  ...                                               0   
1  ...                                               0   
2  ...                                               0   
3  ...                                               0   
4  ...                                               0   

   BC_35 INDOOR PUBLIC AND CULTURAL FACILITIES     \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   BC_36 OUTDOOR RECREATIONAL FACILITIES           \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   BC_37 RELIGIOUS FACILITIES                      \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   BC_38 ASYLUMS AND HOMES                         \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   BC_40 SELECTED GOVERNMENTAL FACILITIES          \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   BC_41 TAX CLASS 4 - OTHER                       TC_1  TC_2  TC_4  
0                                               0     0     1     0  
1                                               0     0     1     0  
2                                               0     0     1     0  
3                                               0     0     1     0  
4                                               0     0     1     0  

[5 rows x 43 columns]

In [56]:
df.shape

(29280, 43)

Siamo pronti per fare machine learning. Separiamo $X$ e $y$.

In [57]:
y = df['SALE PRICE']
X = df.drop(columns=['SALE PRICE'])

In [58]:
X.shape, y.shape

((29280, 42), (29280,))

Per trasformare un DataFrame in un array NumPy possiamo usare il costrutto

        df.values

In [59]:
X_np = X.values

X_np

array([[     5,      0,   1633, ...,      0,      1,      0],
       [    10,      0,   2272, ...,      0,      1,      0],
       [     6,      0,   2369, ...,      0,      1,      0],
       ...,
       [     2,      0,   4000, ...,      1,      0,      0],
       [     0,      7, 208033, ...,      0,      0,      1],
       [     0,      1,  10796, ...,      0,      0,      1]])

<script>
  $(document).ready(function(){
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('div.prompt').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#999; background:#fff;">
Created with Jupyter, delivered by Fastly, rendered by Rackspace.
</footer>